[tox]
envlist = django52, django61
skipsdist = true

[testenv]
basepython = python3.12
skip_install = true
deps =
    pytest
    pytest-django
    django52: Django>=5.2,<5.3
    django61: Django>=6.1,<6.2
commands = pytest {posargs}
